---
- name: Configure NTP on Servers
  hosts: all
  become: true 

  tasks:
    - name: Install NTP Package
      package:
        name: ntp
        state: present
      become: yes

    - name: Start NTP Service and Enable it at Boot
      service:
        name: ntp
        state: started
        enabled: yes
      become: yes
