---
- name: Patch Servers
  hosts: all
  become: true 

  tasks:
    - name: Update package cache (Red Hat)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
      
    - name: Upgrade all packages (Red Hat)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
